name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=dark&hide_border=false&include_all_commits=true
          path: profile/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit stats
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/github-stats.svg
          git commit -m "Update GitHub stats" || exit 0
          git push
